### ISSUE TITLE
TP1

### ISSUE THREAD

**Issue by fbaglivo** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-MauroFab#1]
Por favor, subi el TP1 a github asi se hace mas fácil la corrección.

**Comment by MauroToscano** [comment]
Ahi debería estar todo.

El esquematico quedo solo en el informe porque no encuentro el fuente, cualquier cosa lo creo de nuevo.

**Comment by fbaglivo** [comment]
Estimado, dejo algunos comentarios:

- Por favor utiliza la caratula oficial de la materia que esta en el campus.
- En el esquematio tiene que figurar el microcontrlador con la alimentación, el circuito de reset, el cristal externo, si es que lo usas, y el LED con su R.
- A la lista de materiales agregale los costos de los materiales.
- El link al diagrama de flujos no anda. Mas alla de eso, fijate que el [simbolo](https://www.smartdraw.com/flowchart/simbolos-de-diagramas-de-flujo.htm) que estas usando para los procesos no es el correcto.
- No encuentro el codigo en donde conmutas todo el puerto, esta subido?

Saludos!

Fabricio

**Comment by MauroToscano** [comment]
- Reviso la caratula

- El esquemático no estoy muy seguro de como debería ser. Le puedo agregar el Arduino y sus pines con su conexión por USB a los 5V, pero no estaría muy seguro de que hay que poner del reset.

- Le agrego los costos de lo que compre.

- Corrijo el diagrama.

- Del código subí uno solo, lo comente en el informe. Para no subir todo 2 veces por una linea distinta comente en el código la linea a usar si se quiere conmutar todo el puerto. Igual subo en otro archivo también igual así queda claro.

En un rato subo todas las correcciones, el esquemático capaz me demora un poco más.  Vuelvo a comentar cuando haga los cambios.

**Comment by MauroToscano** [comment]
Dejo un update:

- Subí la caratula con el informe. Use open office para editar el de la cátedra, puede que haya algún cambio ligero de formato, pero creo que quedo bien. Por las dudas además arme una caratula similar para el gdoc, subi el PDF con todo el informe, y deje el link al gdoc de forma que se pueda comentar y editar. Este link esta tanto el readme de la carpeta docs como en la descripción del TP del informe.

- Le agregue los costos de cada material

- Corregí el diagrama de flujo. El link me andaba bien, no funcionan los links del PDF en github, pero si lo bajas anda todo.

- Subí otro código donde anda directamente con el PORTB completo, que igual es el mismo que el otro pero cambiados los comentarios. (Los volví a probar igual los programas por las dudas)

Faltaría el esquemático nada más. Cuando tenga una versión nueva comento de nuevo.

**Comment by MauroToscano** [comment]
Ahi arme un esquemático nuevo. Pregunte a unos compañeros electrónicos y me recomendaron Kicad. Le pude meter un Arduino Mega y con eso salió mejor. 

Le tuve que agregar un puerto USB eso si para ponerle los 5V. Cualquier cosa si se hacía distinto veo de cambiarlo.

**Comment by fbaglivo** [comment]
Hola Mauro: te dejo unos comentarios.

- La caratula que tenes es vieja. Fijate que Jorge Alberto no esta en la catedra hace mucho tiempo. [Aca](https://campus.fi.uba.ar/mod/resource/view.php?id=35037) te dejo el link a la nueva en el campus.
- En el esquematico falta el circuito de reset y el cristal.
-[ Aca](https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-MauroFab/blob/9f1494585b27d94fa17cd2b4e4dacad255a0fb8d/codigo/main_portb_salida.asm#L21) deberias usar out en vez de SBI ( lo mismo mas abajo en vez de CBI)

**Comment by MauroToscano** [comment]
Ya están todos los cambios Fabricio.

Con el circuito de RESET y las conexiones del ATMega con el resto Arduino tengo algunas dudas igual, pero para el esquemático de ahora creo que debería estar todo bien.

**Comment by fbaglivo** [comment]
Hola!

En el circtuito de Reset falta una resistencia entre VCC y el pin de reset.

**Comment by MauroToscano** [comment]
Ahi debería estar, avisame cualquier cosa

**Comment by fbaglivo** [comment]
Hola! Disculpa la demora.

- En la descripcion del trabajo decis que conectas el led a salida 56 del arduino. Si bien es real, el trabajo esta orientado al micro y no al arduino en si. Por favor refrasea ese parrafo.

Lo demas esta ok.

Lo voy a  aprobar pero por favor hace ese cambio.
