### ISSUE TITLE
TP2

### ISSUE THREAD

**Issue by fbaglivo** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-MauroFab#2]
Hola Mauro, acordate de crear un issue cuando subas los informes asi les pegamos una mirada.

**Comment by fbaglivo** [comment]
Hola! Una pregunta. Por que haces esto:

`	NO_APRETADO_LOOP:
		SBIC PUERTO_ENTRADA, BIT_BOTON
		JMP NO_APRETADO_LOOP`

si en teoria cuando el boton no esta apretado el pin esta en '0'? Segun tu esquematico cuando apretas el boton presentas 5V a la entrada.

**Comment by PucciFernando** [comment]
El TP2 está bien. Lo veo un poco pobre con respecto a otros que subieron fotos o videos.
No encuentro errores.
Fijate si podes subir fotos o videos, y responder lo de Fabricio, así se cierra y aprueba
Saludos

**Comment by MauroToscano** [comment]
> El TP2 está bien. Lo veo un poco pobre con respecto a otros que subieron fotos o videos.
> No encuentro errores.
> Fijate si podes subir fotos o videos, y responder lo de Fabricio, así se cierra y aprueba
> Saludos

Le subi un video, esta en el readme. Si no podes acceder avisame. Le sacaría mas fotos pero lo desarme para armar el TP3.  Ahi reviso lo que comento fabricio.

Edit: Te dejo unas fotos también en el readme, pero sin la resistencia de pull up, porque tengo el protoboard medio sobre cargado, y armado con el joystick shield afuera (En el video lo puse arriba). En el video igual jugue un poco con la resistencia pull up ya que use la resistencia variable, asi que se nota que esta andando.

**Comment by MauroToscano** [comment]
> Hola! Una pregunta. Por que haces esto:
> 
> ` NO_APRETADO_LOOP: SBIC PUERTO_ENTRADA, BIT_BOTON JMP NO_APRETADO_LOOP`
> 
> si en teoria cuando el boton no esta apretado el pin esta en '0'? Segun tu esquematico cuando apretas el boton presentas 5V a la entrada.

Cuando lo apretó presento 0V a la entrada. Cuando no apretó hay 5V . Esto lo medí, lo acabo de volver a chequear, y no tengo dudas que esta funcionando así. 

En el esquemático use el símbolo de push to open de Kicad, entiendo que significa que si apretó abre el circuito y tengo 0V (Abierto en realidad) y si no apreto tengo 5V.  ¿Me equivoque de símbolo?

**Comment by PucciFernando** [comment]
Bien, por mi está aprobado, pero antes de cerrarlo quiero que Fabricio lo vea. Las fotos las ví, y se entienden, el video requiere permisos, no está bien compartido.
En el esquemático se ve que es un pulsador normalmente cerrado, eso explica por que hay 5 volts al no apretarlo y 0 al apretarlo.

**Comment by MauroToscano** [comment]
> Bien, por mi está aprobado, pero antes de cerrarlo quiero que Fabricio lo vea. Las fotos las ví, y se entienden, el video requiere permisos, no está bien compartido.

Ahí arregle los permisos!. Te di en particular a vos Fernando, y también lo hice libre para que cualquiera pueda ver. Probé entrar con el link sin estar con mi cuenta y anda.
